version: "3.3"

services:
 shinyproxy:
    image: "private-data/shinyproxy:1.0.1"
    build:
      context: "."
    network_mode: "host"

    ports:
      - 8080:8080

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3

